base_url = "https://abhamra.com"
title = "asb's corner"

# config stuff info here!
# https://not-matthias.github.io/apollo/posts/configuration/#site-configuration

compile_sass = true

theme = "apollo"
default_language = "en"
taxonomies = [{name = "tags"}]

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
author = "Arjun Bhamra"

build_search_index = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"
extra_syntaxes_and_themes = ["syntaxes"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
theme = "toggle"
display_author = true
toc = true
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true
comment = true

menu = [
  { name = "home ~", url = "/", weight = 1 },
  { name = "resume ~", url = "/resume.pdf", weight = 2 },
  { name = "blog", url = "/blog", weight = 3 },
]

socials = [
    { name = "google-scholar", url = "https://scholar.google.com/citations?user=LtdAgHYAAAAJ&hl=en&oi=ao", icon = "google-scholar" },
    { name = "orcid", url = "https://orcid.org/0000-0002-1557-5988", icon = "orcid" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
]
